# Generated by Django 5.1.3 on 2024-11-24 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Employees', 'Employees'), ('Manager', 'Manager')], max_length=50)),
                ('data_of_join', models.DateField(blank=True, null=True)),
                ('salary', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(upload_to='profile_image')),
                ('work_hour', models.PositiveIntegerField(default=8)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
