# Generated by Django 5.1.1 on 2024-11-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='salary',
            new_name='basic_salary',
        ),
    ]
