# Generated by Django 5.1.1 on 2024-11-26 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0003_rename_salary_profile_basic_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_of_join',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
