# Generated by Django 5.1.1 on 2024-11-26 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0005_alter_profile_data_of_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_of_join',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
